### PR TITLE
initial edits and documentation

### PR DESCRIPTION
**Pull request by cengique**
I'm opening this as a placeholder as I'm not done yet, so I'll keep adding commits. But we can start reviewing and commenting.

### CODE REVIEW

**Comment by cengique** [comment]
@dGr8LookinSparky are you merging this in?

**Comment by dGr8LookinSparky** [comment]
@cengique , I'll look into this tomorrow, was there anything else that you wanted to add to this pull request?

**Comment by cengique** [comment]
@dGr8LookinSparky let me at least resolve the conflicts. I'm still not able to run it on my machine, but I think it's the same problem preventing me to run the 1.3 version. Otherwise configure and compile steps were successful.

**Comment by cengique** [comment]
@dGr8LookinSparky I fixed the conflicts and added some more documentation. Let's merge this in if you agree since you are also making changes.

**Comment by cengique** [comment]
@dGr8LookinSparky I had some readme changes here. are you merging this?

**Pull request merged**
